name: EpicTags
version: '${version}'
main: gg.minecrush.epictags.EpicTags
api-version: '1.20'
author: Minecrush

commands:
  admintags:
    aliases: admintag
    description: Manage, create and administrate tags
  tags:
    aliases: tag
    description: Enable and disable tags!